swagger: "2.0"
info:
  description: "This swagger displays the endpoints implemented in the Goals Tracker Microservice."
  version: "1.0"
  title: "Goals Tracker Microservice"
tags:
- name: "Actions"
  description: "Everything about your Goal Tracking"
schemes:
- "https"
paths:
  /actions:
    post:
      tags:
      - "Actions"
      summary: "Add a new goal to the database."
      description: "This operation will add a new goal to the database."
      operationId: "addGoal"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Action items that needs to be added to the database."
        required: true
        schema:
          $ref: "#/definitions/ActionsBody"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ActionsBodyResponse"
        "400":
          description: "Bad Request"
        "403":
          description: "Unauthorized Request"
    get:
      tags:
      - "Actions"
      summary: "Fetch all the goals stored in the database."
      description: "This operation will retrieve all the goals listed in the database."
      operationId: "fetchGoals"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ActionsBodyResponse"
        "400":
          description: "Bad Request"
        "403":
          description: "Unauthorized Request"
  /actions/{id}:
    put:
      tags:
      - "Actions"
      summary: "Update a goal by it's ID"
      description: "This operation will update a single goal"
      operationId: "updateGoalById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the goal which needs to be updated."
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Data that needs to be updated to the database."
        required: true
        schema:
          $ref: "#/definitions/ActionsBody"
      responses:
        "204":
          description: "successful operation"
        "400":
          description: "Bad Request"
        "403":
          description: "Unauthorized Request"
        "404":
          description: "Invalid Identifier"
    get:
      tags:
      - "Actions"
      summary: "Find a goal by it's unique ID"
      description: "This operation will return a single goal object."
      operationId: "getGoalById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The ID of goal to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ActionsBodyResponse"
        "400":
          description: "Bad Request"
        "403":
          description: "Unauthorized Request"
        "404":
          description: "Invalid Identifier"
    delete:
      tags:
      - "Actions"
      summary: "Deletes a goal"
      description: "This operation will delete the goal associated with the ID provided."
      operationId: "deleteGoal"
      parameters:
      - name: "id"
        in: "path"
        description: "Goal id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "204":
          description: "successful operation"
        "400":
          description: "Bad Request"
        "403":
          description: "Unauthorized Request"
        "404":
          description: "Invalid Identifier"
definitions:
  ActionsBody:
    type: "object"
    properties:
      goal:
        type: "string"
        example: "Workout for 2 hours everyday."
      createdOn:
        type: "string"
        example: "2021-02-03T12:00:00+00:00"
      deadline:
        type: "string"
        example: "2021-02-03T12:00:00+00:00"
      isCompleted:
        type: "boolean"
        example: true
      completedOn:
        type: "string"
        example: "2021-02-03T12:00:00+00:00"
  ActionsBodyResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      goal:
        type: "string"
        example: "Workout for 2 hours everyday."
      createdOn:
        type: "string"
        example: "2021-02-03T12:00:00+00:00"
      deadline:
        type: "string"
        example: "2021-02-03T12:00:00+00:00"
      isCompleted:
        type: "boolean"
        example: true
      completedOn:
        type: "string"
        example: "2021-02-03T12:00:00+00:00"
